name: build_openwrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04

    steps:
    - name: step1
      uses: actions/checkout@v4

    - name: step2
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext unzip zlib1g-dev file python3-distutils python3

    - name: step3
      run: |
        git clone https://openwrt.org openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: step4
      run: |
        cd openwrt
        echo "CONFIG_TARGET_ar71xx=y" > .config
        echo "CONFIG_TARGET_ar71xx_generic=y" >> .config
        echo "CONFIG_TARGET_ar71xx_generic_PROFILE_TLMR3420V2=y" >> .config
        echo "CONFIG_IPV6=n" >> .config
        echo "CONFIG_PACKAGE_odhcp6c=n" >> .config
        echo "CONFIG_PACKAGE_odhcpd=n" >> .config
        echo "CONFIG_PACKAGE_ip6tables=n" >> .config
        make defconfig

    - name: step5
      run: |
        cd openwrt
        make -j$(nproc) V=s

    - name: step6
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_15.05_MR3420v2_NoIPv6
        path: openwrt/bin/
