name: Build OpenWrt 15.05 for MR3420v2 without IPv6

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext unzip zlib1g-dev file python3

    - name: Clone source code
      run: |
        PART1="https:/"
        PART2="github.com"
        PART3="openwrt"
        git clone -b chaos_calmer "$PART1/$PART2/$PART3/$PART3.git"
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure and Patch IPv6 out
      run: |
        cd openwrt
        
        echo "CONFIG_TARGET_ar71xx=y" > .config
        echo "CONFIG_TARGET_ar71xx_generic=y" >> .config
        echo "CONFIG_TARGET_ar71xx_generic_PROFILE_TLMR3420V2=y" >> .config
        
        echo "CONFIG_IPV6=n" >> .config
        echo "CONFIG_PACKAGE_odhcp6c=n" >> .config
        echo "CONFIG_PACKAGE_odhcpd=n" >> .config
        echo "CONFIG_PACKAGE_ip6tables=n" >> .config
        
        make defconfig

    - name: Compile firmware
      run: |
        cd openwrt
        make -j$(nproc) V=s

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_15.05_MR3420v2_NoIPv6
        path: openwrt/bin/
