name: build_openwrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04

    steps:
    - name: step1
      uses: actions/checkout@v4

    - name: step2
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y build-essential gawk gettext unzip file wget python3 ccache

    - name: step3
      run: |
        A="downloads"
        B="openwrt"
        C="org"
        D="chaos_calmer/15.05.1/ar71xx/generic"
        E="OpenWrt-ImageBuilder-15.05.1-ar71xx-generic.Linux-x86_64"
        wget https://$A.$B.$C/$D/$E.tar.bz2
        tar -xjf $E.tar.bz2
        mv $E ib && cd ib
        
        # Вырезаем IPv6/PPP и добавляем пакеты для работы USB веб-камеры
        make image PROFILE="TLMR3420" PACKAGES="-odhcp6c -odhcpd -ip6tables -luci-proto-ipv6 -kmod-ipv6 -kmod-ip6tables -ppp -ppp-mod-pppoe -kmod-usb-net-ipheth -luci-proto-ppp kmod-video-core kmod-video-uvc libjpeg mjpg-streamer"

    - name: step4
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_15.05_MR3420v2_Webcam_Server
        path: ib/bin/
